const mongoose=require("mongoose")
const Schema=new mongoose.Schema({
    filename:{
        type:String,
        required:true
    },
    dev:{
        required:true,
        type:Number
    },
    mode:{
        required:true,
        type:Number
    },
    nlink:{
        required:true,
        type:Number
    },
    uid:{
        required:true,
        type:Number
    },
    gid:{
        required:true,
        type:Number
    },
    rdev:{
        required:true,
        type:Number
    },
    blksize:{
        required:true,
        type:Number
    },
    ino:{
        required:true,
        type:Number
    },
    size:{
        required:true,
        type:Number
    },
    blocks:{
        required:true,
        type:Number
    },
    atimeMs:{
        required:true,
        type:Number
    },
    mtimeMs:{
        required:true,
        type:Number
    },
    ctimeMs:{
        required:true,
        type:Number
    },
    birthtimeMs:{
        required:true,
        type:Number
    },
    atime:{
        required:true,
        type:Date
    },
    mtime:{
        required:true,
        type:Date
    },
    ctime:{
        required:true,
        type:Date
    },
    birthtime:{
        required:true,
        type:Date
    },
},{collection:"data"})
module.exports=mongoose.model("schema",Schema)